code_doc/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView

from .views import global_views, project_views, author_views, artifact_views, revision_views
from code_doc.views import series_views

urlpatterns = [
    url(r'^$', global_views.index, name='index'),
    url(r'^about$', global_views.about, name='about'),
    url(r'^script$', global_views.script, name='script'),

    url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', LogoutView.as_view(), name='logout'),

    # topics
    # lists all topics
    url(r'^topics/$',
        global_views.TopicListView.as_view(),
        name='topics_list'),
    # gives details on a specific topic
    url(r'^topics/(?P<topic_id>\d+)/$',
        global_views.TopicView.as_view(),
        name='topic'),

    # projects
    # lists all projects
    url(r'^project/$', project_views.ProjectListView.as_view(), name='project_list'),
    # details of a particular project
    url(r'^project/(?P<project_id>\d+)/$', project_views.ProjectView.as_view(), name='project'),

    # Series
    # lists all series of a project
    url(r'^series/(?P<project_id>\d+)/$',
        project_views.ProjectView.as_view(),
        name='project_series_all'),
    # details about a particular series of a project
    url(r'^series/(?P<project_id>\d+)/(?P<series_id>\d+)/$',
        series_views.SeriesDetailsView.as_view(),
        name='project_series'),
    # edition of a particular project series
    url(r'^project/(?P<project_id>\d+)/(?P<series_id>\w+)/edit',
        series_views.SeriesUpdateView.as_view(),
        name='project_series_edit'),
    # adding a revision to the project
    url(r'^series/(?P<project_id>\d+)/add/$',
        series_views.SeriesAddView.as_view(),
        name='project_series_add'),
    # adding user to a particular project series
    url(r'^project/(?P<project_id>\d+)/(?P<series_id>\w+)/add_user',
        global_views.ModalAddUserView.as_view(),
        name='project_series_add_user'),
    # adding grouop to a particular project series
    url(r'^project/(?P<project_id>\d+)/(?P<series_id>\w+)/add_group',
        global_views.ModalAddGroupView.as_view(),
        name='project_series_add_group'),

    # Revisions
    # See the contents of a revision
    url(r'^revision/(?P<project_id>\d+)/(?P<revision_id>\d+)/$',
        revision_views.RevisionDetailsView.as_view(),
        name='project_revision'),

    # @todo update and delete of a series

    # project series artifacts
    # url(r'^project/(?P<project_id>\d+)/(?P<series_number>[\d\w\s]+)/$',
    #    series_views.ProjectSeriesArtifactView.as_view(),
    #    name='project_artifacts'),
    url(r'^artifacts/(?P<project_id>\d+)/(?P<series_id>\w+)/add$',
        artifact_views.ArtifactAddView.as_view(),
        name='project_artifacts_add'),
    url(r'^artifacts/(?P<project_id>\d+)/(?P<series_id>\w+)/remove/(?P<artifact_id>\w+)',
        artifact_views.ArtifactRemoveView.as_view(),
        name='project_artifacts_remove'),
    url(r'^artifacts/api/(?P<project_id>\d+)/(?P<series_id>\w+)/$',
        series_views.APIGetSeriesArtifacts.as_view(),
        name='api_get_artifacts'),

    # shortcuts
    url(r'^s/(?P<project_name>[\d\w\s]+)/(?P<series_number>[\d\w\s]+)/$',
        series_views.SeriesDetailsViewShortcut.as_view(),
        name='project_shortcuts'),
    url(r'^api/(?P<project_name>[\d\w\s-]+)/(?P<series_number>[\d\w\s-]+)/$',
        project_views.GetProjectRevisionIds.as_view(),
        name='api_get_ids'),

    # get all usernames
    url(r'^api/get_usernames/',
        global_views.JSONResponseUsernamesView.as_view(),
        name='api_usernames'),

    # get all group names
    url(r'^api/get_groupnames/',
        global_views.JSONResponseGroupnamesView.as_view(),
        name='api_groupnames'),

    # maintainers
    url(r'^maintainer/(?P<maintainer_id>\d+)/$',
        author_views.MaintainerProfileView.as_view(),
        name='maintainer'),

    # Authors
    # lists all authors
    url(r'^authors/$',
        author_views.AuthorListView.as_view(),
        name='authors_list'),
    # details about an author
    url(r'^authors/(?P<author_id>\d+)/$',
        author_views.detail_author,
        name='author'),
    url(r'^authors/(?P<author_id>\d+)/edit$',
        author_views.AuthorUpdateView.as_view(),
        name='author_edit'),

]

www/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

from django.contrib import admin

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('code_doc.urls')),
]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

code_doc/models/projects.py
from django.db import models
from django.contrib.auth.models import Group
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.conf import settings

import logging

from .models import Topic, Copyright, CopyrightHolder, manage_permission_on_object
from .authors import Author

logger = logging.getLogger(__name__)


class Project(models.Model):
    """A project, may contain several authors"""
    name = models.CharField(max_length=50, unique=True)
    short_description = models.TextField('short description of the project (200 chars)',
                                         max_length=200,
                                         blank=True,
                                         null=True)
    description_mk = models.TextField('text in Markdown', max_length=2500, blank=True, null=True)
    icon = models.ImageField(blank=True, null=True, upload_to='project_icons/')
    slug = models.SlugField()

    #: Authors of the project
    authors = models.ManyToManyField(Author)

    # the administrators of the project, have the rights to edit the project
    administrators = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                            blank=True)

    #: Home page of the project
    home_page_url = models.CharField(max_length=250, null=True, blank=True)

    #: Copyright/license of the project
    copyright = models.ForeignKey(Copyright,
                                  null=True,
                                  blank=True,
                                  on_delete=models.SET_NULL)

    #: Copyright holders of the project
    copyright_holder = models.ManyToManyField(CopyrightHolder, blank=True)

    #: Topics covered by the project
    topics = models.ManyToManyField(Topic, blank=True)

    nb_revisions_to_keep = models.IntegerField("default number of revisions to keep",
                                               default=None,
                                               blank=True,
                                               null=True)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('project', kwargs={'project_id': self.pk})

    class Meta:
        permissions = (
            ("project_view", "User/group can see the project"),
            ("project_administrate", "User/group administrates the project"),
            ("project_series_add", "User/group can add a series to the project"),
            ("project_series_delete", "User/group can delete a series from the project"),
            ("project_artifact_add", "Can add an artifact to the project"),  # to remove
        )

    def has_user_project_administrate_permission(self, user):
        """Returns true if the user is able to administrate a project"""
        return user.is_superuser or user in self.administrators.all()

    def has_user_project_view_permission(self, user):
        """Returns true if the user is able to view the project"""
        return True

    def has_user_project_series_add_permission(self, user):
        """Returns true if the user is able to add series to the current project"""
        return self.has_user_project_administrate_permission(user)

    def has_user_project_series_delete_permission(self, user):
        """Returns true if the user is able to add series to the current project"""
        return self.has_user_project_administrate_permission(user)

    def has_user_project_artifact_add_permission(self, user):
        """Returns true if the user is able to add series to the current project"""
        return self.has_user_project_administrate_permission(user)

    def get_number_of_files(self):
        """Returns the number of files archived for a project"""
        artifact_counts = [rev.artifacts.count() for rev in self.series.all()]
        return sum(artifact_counts) if len(artifact_counts) > 0 else 0

    def get_number_of_series(self):
        """Returns the number of series for a project"""
        return self.series.count()

    def get_number_of_revisions(self):
        """Returns the number of revisions for a project"""
        return self.revisions.count()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)  # Call the "real" save() method.


class ProjectRepository(models.Model):
    """Represents a project repository"""

    #: The project
    project = models.ForeignKey(Project,
                                related_name='repositories',
                                on_delete=models.CASCADE)

    #: The related repository
    code_source_url = models.CharField(max_length=500,
                                       null=False,
                                       blank=False)

    class Meta:
        unique_together = (("project", "code_source_url"),)
        verbose_name_plural = "Project repositories"

    def get_absolute_url(self):
        return reverse('project', kwargs={'project_id': self.project.id})

    def __str__(self):
        return "[%s] %s" % (self.project.name, self.code_source_url)


class ProjectSeries(models.Model):
    """A series of a project comes with several artifacts"""
    #: The project reference
    project = models.ForeignKey(Project,
                                related_name="series",
                                on_delete=models.CASCADE)

    #: The series name
    series = models.CharField(max_length=500)  # can be a hash

    #: Release date
    release_date = models.DateField('Release date')

    #: Indicates if a series is publicly accessible
    is_public = models.BooleanField(default=False)

    #: Description of this series
    description_mk = models.TextField('Description in Markdown format',
                                      max_length=2500,
                                      blank=True,
                                      null=True)

    nb_revisions_to_keep = models.IntegerField("default number of revisions to keep. Overrides the "
                                               "projects default",
                                               default=None,
                                               blank=True,
                                               null=True)

    # the users and groups allowed to view the artifacts of the revision
    # and also this project series
    view_users = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        blank=True,
                                        related_name='view_users')
    view_groups = models.ManyToManyField(Group,
                                         blank=True,
                                         related_name='view_groups')

    perms_users_artifacts_add = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                                       blank=True,
                                                       related_name='perms_users_artifacts_add')
    perms_groups_artifacts_add = models.ManyToManyField(Group,
                                                        blank=True,
                                                        related_name='perms_groups_artifacts_add')

    perms_users_artifacts_del = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                                       blank=True,
                                                       related_name='perms_users_artifacts_del')
    perms_groups_artifacts_del = models.ManyToManyField(Group,
                                                        blank=True,
                                                        related_name='perms_groups_artifacts_del')

    class Meta:
        verbose_name_plural = "Project series"
        unique_together = (("project", "series"),)
        permissions = (
            ("series_view", "User/group has access to this series and its content"),
            ("series_edit", "User/group can edit the definition of this series"),
            ("series_artifact_add", "User/group is allowed to add an artifact"),
            ("series_artifact_delete", "User/group is allowed to delete an artifact"),
        )

    def __str__(self):
        return "[%s @ %s] [%s]" % (self.project.name, self.series, self.release_date)

    def get_absolute_url(self):
        return reverse('project_series', kwargs={'project_id': self.project.pk,
                                                 'series_id': self.pk})

    def has_user_series_view_permission(self, userobj):
        """Returns true if the user has view permission on this series, False otherwise"""
        return self.is_public or \
            self.project.has_user_project_administrate_permission(userobj) or \
            self.has_user_series_edit_permission(userobj) or \
            self.has_user_series_artifact_add_permission(userobj) or \
            manage_permission_on_object(userobj, self.view_users, self.view_groups, False)

    def has_user_series_edit_permission(self, userobj):
        """Returns true if the user has edit permission on this series, False otherwise

        The edit permission if not granted if the user has the artifact add role. However, since the
        redirection to the artifact add is the session edition form, the associated view should
        also check for this permission.
        """
        return self.project.has_user_project_administrate_permission(userobj)

    def has_user_series_artifact_add_permission(self, userobj):
        """Returns True if the user can add an artifact to the serie"""
        return \
            self.project.has_user_project_administrate_permission(userobj) or \
            manage_permission_on_object(userobj,
                                        self.perms_users_artifacts_add,
                                        self.perms_groups_artifacts_add, False)

    def has_user_series_artifact_delete_permission(self, userobj):
        """Returns True if the user can remove an artifact from the serie"""

code_doc/views/author_views.py
from django.shortcuts import render
from django.http import Http404

from django.views.generic.edit import UpdateView
from django.views.generic import ListView, View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator


import logging

from ..models.projects import Project
from ..models.authors import Author
from ..forms.forms import AuthorForm
from .permission_helpers import PermissionOnObjectViewMixin

# logger for this file
logger = logging.getLogger(__name__)


class AuthorListView(ListView):
    """A generic view of the authors in a list"""
    paginate_by = 10
    template_name = "code_doc/authors/author_list.html"
    context_object_name = "authors"
    model = Author


def detail_author(request, author_id):
    try:
        author = Author.objects.get(pk=author_id)
    except Author.DoesNotExist:
        raise Http404

    project_list = Project.objects.filter(authors=author)
    coauthor_list = Author.objects.filter(project__in=project_list).distinct().exclude(pk=author_id)

    return render(request,
                  'code_doc/authors/author_details.html',
                  {'project_list': project_list,
                   'author': author,
                   'user': request.user,
                   'coauthor_list': coauthor_list})


class AuthorUpdateView(PermissionOnObjectViewMixin, UpdateView):
    """View for editing information about an Author

      .. note:: in order to be able to edit an Author, the user should have the
                'code_doc.author_edit' permission on the Author object.
    """

    form_class = AuthorForm
    model = Author

    permissions_on_object = ('code_doc.author_edit',)
    permissions_object_getter = 'get_author_from_request'

    template_name = "code_doc/authors/author_edit.html"

    pk_url_kwarg = 'author_id'

    def get_author_from_request(self, request, *args, **kwargs):
        # TODO check if needed
        try:
            return Author.objects.get(pk=kwargs['author_id'])
        except Author.DoesNotExist:
            logger.warning('[AuthorUpdateView] non existent Author with id %s',
                           kwargs['author_id'])
            return None


class MaintainerProfileView(View):
    """Manages the views associated to the maintainers"""

    @method_decorator(login_required)
    def get(self, request, maintainer_id):
        try:
            maintainer = User.objects.get(pk=maintainer_id)
        except Project.DoesNotExist:
            raise Http404

        projects = Project.objects.filter(administrators=maintainer)
        return render(request,
                      'code_doc/maintainer_details.html',
                      {'projects': projects,
                       'maintainer': maintainer})

    @method_decorator(login_required)
    def post(self, request):
        pass

code_doc/templates/code_doc/about.html
{% extends "code_doc/base_template.html" %}
{% load gravatar %}
{% load static %}
{% load project_image %}
{% load markdown_filter %}

{% block title %}About Code.Doc{% endblock %}

{% block content %}

{% markdown_tag %}

Welcome to the [code_doc](https://bitbucket.org/renficiaud/code_doc) project!
============================

The main purposes of this web application is to easily publish the documentation (and any other artifact) 
associated to your code repository. Those artifacts are the result of some build process of your own on
a build server or on your computer.

`code_doc` aims at the following:

* helps users or potential users discover your projects, its description, features, licensing, copyright, authors...
* helps developers of the project access the API without effort or action: the stored documentation is
  accessible through a browser,
* focus on dynamic content: documentation/artifacts can be pushed to the server from a python script, which makes easy
  the update of the docs when the code is updated,
* storing the documentation and binaries that you want to share, publicly or with your team mates,
* making your projects available to the public or to specific groups and increase their visibility

`code_doc` is powered by [Django](https://www.djangoproject.com/) and is fully [open source](https://bitbucket.org/renficiaud/code_doc). 
The project has a minimual set of dependencies. You are welcome to contribute!

----------------------------

[TOC]


----------------------------

What are the functionalities offered?
=====================================

* suitable for code: each artifact you upload may optionally be associated to a revision and a branch, which eases tracking 
  which version of your code produced the artifact
* Organization into series: a project contains one or more series, each of which having its set of artifacts. Artifacts may
  be shared among several series. This is particularly useful when an artifact is promoted eg. from `develop` to `master` or
  `stable` series.  
* Possibility to upload or update archives, documentation or any kind of artifact directly from a script: this make it convenient
  to plug `code_doc` to your prefered Continuous Build System. The update is done simply with a python script that sends
  the artifacts to the appropriate place.
* The uploaded documentation is not interpreted in any way: it is possible to upload an archive containing HTML or text files
  generated by a wide range of documentation tools (Docbook, Doxygen, Matlab, Sphinx, etc.) as long as this file can be 
  served by a browser.
* Offers fine permissions management: you work on a private personal project, and you want to share the advance within a restricted group
  of people? Your project is public and you want to make it available to anyone?
  `code_doc` addresses these constraints and adapts to various kind of work environment. 
  No need to set up different private servers: only one instance with the proper authorization on project and series.


----------------------------

Ready to set up?
==================

You are certainly convinced by the usefulness (or necessity) of this web site. In the sequel, the three main objects
manipulated by `code_doc` will be detailed.

The two ingredients for being able to push *things* on this server are

* Defining a project
* Defining one or more series for this project


A project contains the following informations:

* the purpose of the project and the services it provides
* how to use the source or binary code (copyrights, location of the source code)
* its maintainers and how to contact them
* its authors
* and a list of series

A series is composed of

* a name
* a description which indicates the purpose of the series (continuous build, /release/, /stable/, /developments/, /experimental/ ...)
* a release date
* a set of permissions indicating what operations are granted to each user/group
* a list of artifacts that can either be single files or archives containing documentation

## Create a project
At the moment, creating a project is an *admin* privilege, so you should ask your administrator to create a project for you.
A project has one or more **maintainers** that have full access to all functionalities for this particular project (`maintainer`
access).

## Create a series
You can create a new series if you have the proper credentials on the project. If this is the case, a "+" button is active right to the 
"Series" header on the project page.

When the series is created, the access rights given to the users or groups of users may be specified. Different type of access are 
provided:

* either the series is public: everybody, logged in or not, is able to download or visualize the artifacts contained in the series. 
  However it is not possible to add or remove an artifact without the proper privileges.
* or the series is restricted: specific users/groups are allowed to read, add or remove artifacts. 

!!! alert "Note"
    Please note that `remove` permission grants automatically `add` permission, and `add` permission grants `view`. 

## Add an artifact
Now that the series is created, one or several artifacts may be added to it. An artifact is more or less a file with some meta-data
that changes the way it is visualized by the application.

It is possible to add an artifact from the web interface or from the command line (detailed below). An artifact may come 
with a revision and/or a branch, which may be created on-the-fly during the upload. Also an artifact may belong to several series 
(for instance an artifact from `continuous` may be promoted to `stable` or `release` series). 

!!! alert
    In order to be able to add an artifact to a series, the user/group should have the `add` permission at the series level, or
    an admin access to the project.

### Revisions and branches
In order to be able to track artifacts with respect to the code that generated those, it is possible to associate an artifact with
a **revision** (number or string):

* A revision may contain several artifacts, but an artifact belongs to at most one revision.
* A revision may be part of one or more branches, a branch may contain several revisions (see `git` for instance).

### Command line upload of an artifact

One of the nice functionalities of *code doc* is to be able to push artifacts on the server. This enables the project/series content to be
update from a build server for instance.

The following steps should be followed:

* have proper credentials that allows you to upload something on this server
* Download [the script]({% url 'script' %}) manually from here or automatically as follow:

        :::bash
        wget {{request.scheme}}://{{request.get_host}}{% url 'script' %} -O script.py

* Create a task in your build scheme that uploads the artifact. For regular artifacts (not documentation):

        :::bash
        python script.py -s {{request.scheme}}://{{request.get_host}} --username=user --password=pass \
               --project="project-name" --artifact_series="stable" \
               -f filetosend.tar.bz2
  
      For documentation, you have to specify an additional flag, `--is_doc` and the main entry point of the documentation with `--doc_entry`:

        :::bash
        python script.py -s {{request.scheme}}://{{request.get_host}} --username=$USER --password=$PASS \
               --project="project-name" --artifact_series="night-builds" \
               --is_doc --doc_entry=my_tar_content/index.html \
               -f filetosend.tar.bz2

The parameters of the upload script are the following:

* `--project` the project to which the artifact belongs. This parameter is *necessary*.
* `--artifact_series` the series to which the artifact will be first stored. This parameter is *necessary*.
* `--file` the file to send. This parameter is *necessary*.
* `--artifact_branch` specifies the branch of the artifact (case sensitive). If the branch is specified and not empty, the revision should
  also be specified.
* `--artifact_revision` indicates the revision of the artifact (case sensitive)
* `--is_doc` if set, indicates that the uploaded file is an archive containing a documentation. In that case `--doc_entry` should be specified
* `--doc_entry` the entry point for the documentation, relative to the root of the deflated archive. The web application
  will serve this file as an entry point for viewing/parsing the documentation
* `--artifact_description` a short description of the artifact  

### Limiting the number of revisions
It is possible to limit the number of revisions at the series level. Each artifact may or not be associated to one unique revision, but a
revision may contain several artifacts. If the series does not have any restriction on this limit (0 or blank), the project default is used
instead. If in turn the project does not have any limit neither, all artifacts are kept.

!!! alert "Remark"
    In case the artifact is not associated to any revision, it is considered as having a *dedicated* revision.

Once the limit over the revisions is reached, all artifacts of the oldest revisions are dissociated from the series:

* a revision is **deleted** if it is not associated to any series,
* a revision is **deleted** when it does not contain any artifact,
* an artifact is **deleted** when it does not belong to any series


## Associating users and authors
It is possible to associate a user with an author. In that case, the associated user may edit the details of the author, otherwise
this permission is granted only to the `admin` of the web application.


Markdown format
---------------
Some fields (mostly description) use the [Markdown](http://daringfireball.net/projects/markdown/) format for having a richer
formatting. 
 
[markdown](http://pythonhosted.org/Markdown/index.html) extension and the code highlighter [pygments](http://pygments.org/). 

To insert some code as explanation, you can do the following

    :::bash
    :::bash
    pip install my_package

If the block above is indented with 4 spaces, then Markdown interprets it as code with the designated language. You can also do

    #!bash
    #!bash
    pip install my_package

instead, and in this case the lines will be numbered. These code blocks can be nested with lists (the indentation then becomes 8 spaces).


----------------------------

# Deployment

The deployment part is a bit out of scope of the current document, and is detailed on the [wiki](https://bitbucket.org/renficiaud/code_doc/wiki/Home)
pages of the project.

----------------------------


{% endmarkdown_tag %}

{% endblock %}

code_doc/templates/code_doc/index.html
{% extends "code_doc/base_template.html" %}
{% load gravatar %}
{% load static %}
{% load project_image %}

{% block title %}MPI.IS documentation and download center{% endblock %}

{% block content %}
  <div class="jumbotron">
    <div class="row">
      <div class="col-md-8">
        <h1>Documentation and download center</h1>
        <h3>Software Workshop</h3>
        <p>The Max Planck Institute for Intelligent Systems loves softwares, and loves reading documentation!</p>
        <p><a class="btn btn-primary btn-lg" role="button" href="{% url 'about' %}">Learn more</a></p>
      </div>
      <div class="col-md-4">
        
        <img class="media-object" src="{% get_static_prefix %}minerva_01.png" width="300px" />
      </div>
    </div>
  </div>


  <h2>Projects</h2>
  <p>You will find below a shorted list of Softwares and Libraries maintained by the Max Planck Institute for Intelligent Systems at Tübingen. 
     Click on a project for more details, or visit <a href="{% url 'project_list' %}">this page</a> for the complete list.
  </p>


{% if list_project_per_line %}
    
  {% for current_project_line in list_project_per_line %}
  
  <div class="row">
  {% for current_project in current_project_line %}
  <div class="col-md-{{ size_row }}">
    {% if current_project %}
    <div class="panel panel-default">
      <div class="panel-body" style="max-height: 50;">
         <p class="lead"><a href="{{ current_project.get_absolute_url }}">
         {% project_image current_project.id 32 '' %}{{ current_project.name }}
        </a>
        </p>
        <p>{{ current_project.short_description }}</p>
      </div>
    </div>
    {% endif %}
  </div>
  {% endfor %}
  </div>
  
  {% endfor %}

{% else %}
  <p>No registered project.</p>
{% endif %}


<h2>Topics</h2>
{% if list_topic_per_line %}
  
  
  {% for current_topic_line in list_topic_per_line %}
      <div class="row">
      {% for topic in current_topic_line %}
      <div class="col-md-{{ size_row }}">
      <ul class="nav nav-pills nav-stacked">
      
      <li class="active">
        {% if topic %}
        <a href="{{ topic.get_absolute_url }}" >
          <span class="badge pull-right color-red"> {{topic.project_set.count}} </span>
          {{ topic.name }}
        </a>
        {% endif %}
      </li>
      
      </ul>
      </div>
      {% endfor %}
    
      </div>  
  {% endfor %}
  
  
{% else %}
  <p>No registered topic.</p>
{% endif %}

{% endblock %}